POST http://localhost:3333/videos 
Content-Type: application/json

{
    "title": "Video node",
    "description": "Video 1 description",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/c5b79a8d-ee34-42b2-ae1d-5b7f593114d8
Content-Type: application/json

{
    "title": "Video 2",
    "description": "Video 13 description",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/c5b79a8d-ee34-42b2-ae1d-5b7f593114d8